name:                csb-sim
version:             0.1.0.0
github:              "abt8601/csb-sim"
license:             PublicDomain
author:              "Po-Yi Tsai"
maintainer:          "abt8601@protonmail.ch"
copyright:           "2020 Po-Yi Tsai"

extra-source-files:
- README.md
#- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/abt8601/csb-sim#readme>

dependencies:
- base >= 4.7 && < 5
- vector

library:
  source-dirs: src

default-extensions:
  - DeriveFunctor

#executables:
#  csb-sim-exe:
#    main:                Main.hs
#    source-dirs:         app
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - csb-sim

tests:
  csb-sim-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - csb-sim
